version: '3.5'

services:
  db:
    container_name: postgressql
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    image: postgres:14.3-alpine
  bot:
    build: .
    restart: always
    depends_on:
      - db
